### ISSUE TITLE
how to use proxy

### ISSUE THREAD

**Issue by suryacandra** [JijaProGamer/youtubeWatchBot#1]
how to use proxy? always unusable. i have premium proxy aswell

**Comment by JijaProGamer** [comment]
Can you show me your options file? Also what error do you receive?

**Comment by suryacandra** [comment]
> Can you show me your options file? Also what error do you receive?

i also use no proxy but always throw error "Please call api.initWatcher on this page first"
![image](https://user-images.githubusercontent.com/61748274/209475911-d687dd1e-a328-4199-8442-1b03f4dcbdc1.png)


my options :
![image](https://user-images.githubusercontent.com/61748274/209475887-f738b61a-1058-49bb-8376-ba2504ca8cc8.png)

**Comment by JijaProGamer** [comment]
That error is called when the style is incorrect, and style doesn't really refear to the type of content you are posting, but it actually refers to how to watch the video 
(direct = just go to the url, search = search the video, subscriptions = log in and search subscriptions, only for usage with accounts inserted)
You must change style to

```
["search", "direct"]
```

Also if you want more than 3 views generated (Youtube will remove most of anyways, since it seems you are only using the direct:// proxy which means it will only use one IP) you need to change the guest_views argument

 and it will only watch the 42 seconds of the video, you can change it to 75%-85% or another value of your likeness

**Comment by suryacandra** [comment]
> That error is called when the style is incorrect, and style doesn't really refear to the type of content you are posting, but it actually refers to how to watch the video (direct = just go to the url, search = search the video, subscriptions = log in and search subscriptions, only for usage with accounts inserted) You must change style to
> 
> ```
> ["search", "direct"]
> ```
> 
> Also if you want more than 3 views generated (Youtube will remove most of anyways, since it seems you are only using the direct:// proxy which means it will only use one IP) you need to change the guest_views argument
> 
> and it will only watch the 42 seconds of the video, you can change it to 75%-85% or another value of your likeness

wait how to use https proxy i try https://user:pass:ip:port and https://user:pass@ip:port its not worked always unusable also trying sock5 like in your readme but still same

**Comment by JijaProGamer** [comment]
Its supposed to work with https://user:pass@ip:port , maybe your proxy is not working. Can you try 

```
C:\Program Files (86)\Google\Chrome\Application\chrome.exe --proxy-server=https://user:pass@ip:port
```

in a console on your computer and see if it works? Of course, change https://user:pass@ip:port to your server (and protocol if its not https)

**Comment by suryacandra** [comment]
> Its supposed to work with https://user:pass@ip:port , maybe your proxy is not working. Can you try
> 
> ```
> C:\Program Files (86)\Google\Chrome\Application\chrome.exe --proxy-server=https://user:pass@ip:port
> ```
> 
> in a console on your computer and see if it works? Of course, change https://user:pass@ip:port to your server (and protocol if its not https)

it work perfectly using direct, but still cant use my proxy. i can use the proxy in [MShawon](https://github.com/MShawon) /
[YouTube-Viewer](https://github.com/MShawon/YouTube-Viewer) and trying that command cant browsing anything. i still dont understand why too

**Comment by suryacandra** [comment]
> Its supposed to work with https://user:pass@ip:port , maybe your proxy is not working. Can you try
> 
> ```
> C:\Program Files (86)\Google\Chrome\Application\chrome.exe --proxy-server=https://user:pass@ip:port
> ```
> 
> in a console on your computer and see if it works? Of course, change https://user:pass@ip:port to your server (and protocol if its not https)

it work perfectly using direct, but still cant use my proxy. i can use the proxy in [MShawon](https://github.com/MShawon) /
[YouTube-Viewer](https://github.com/MShawon/YouTube-Viewer) and trying that command cant browsing anything. i still dont understand why too

**Comment by JijaProGamer** [comment]
If its not working with that command it means your proxy is not compatible with google chrome

**Comment by suryacandra** [comment]
> If its not working with that command it means your proxy is not compatible with google chrome

where i can get proxy that support this? or its just my isp ?

**Comment by JijaProGamer** [comment]
You could try to send the proxy url to me in private, or if you are not comfortable with that, try to make sure its protocol://user:password@ip:port . Example; http://cool:coolpassword*197.322.128.98:80
If its still not working, the only solution is to try to send it in private to me or to try to debug further by yourself

**Comment by suryacandra** [comment]
thanks for helping me out, all worked perfectly now. it looks like the problem was from my proxy provider

**Comment by JijaProGamer** [comment]
Okay, I guess I can close the issue as solved now?

**Comment by JijaProGamer** [comment]
It means your proxy or internet is too slow, and after 30 seconds of waiting google chrome just stopped trying to load

**Comment by furjac** [comment]
bro for bot can we use any type of proxy or only http

**Comment by JijaProGamer** [comment]
> bro for bot can we use any type of proxy or only http

socks4, socks5 and http

**Comment by furjac** [comment]
ok thanks

**Comment by furjac** [comment]
how much views can i give from a one premium proxy i cant understand the premium proxy

**Comment by JijaProGamer** [comment]
Around 3-4 views per proxy is good, any more than that and youtube may remove some views
