### ISSUE TITLE
Can you help me using IPRoyal Residential proxies ?

### ISSUE THREAD

**Issue by hanbit77** [JijaProGamer/youtubeWatchBot#2]
I got IPRoyal Residential proxies from https://iproyal.com/ .
I didn't pass the proxy check in your bot. 
If I comment out proxy_tester function, then your bot is working.
But, I don't know whether the proxy server is working or not.
Can  you help me?

**Comment by JijaProGamer** [comment]
Is the Iproyal having authentification (user:password@ip:port) format? If it doesnt, then you can start a chrome browser and put the proxy in and see how fast it loads youtube, if its longer than 30 seconds then it wont work

P.S: I dont reccomend IPRoyal, many people were having problems with IPRoyal but not other proxy providers

**Comment by hanbit77** [comment]
Yes! the format is the form of (user:password@ip:port).
I set the timeout to 30 secs.

Can you recommend the proxy server? 
Then I'll test the server.

**Comment by JijaProGamer** [comment]
Personally I use webshare, but plan on switching providers soon

**Comment by hanbit77** [comment]
Thanks~! 
I'll wait for your proxy server plan.

**Comment by JijaProGamer** [comment]
You can try direct:// instead of a proxy and check if it works

**Comment by hanbit77** [comment]
direct:// method is working very well.

**Comment by JijaProGamer** [comment]
That means that your internet is working good and the bot has no problems, but your proxy may be at fault. Try at IPRoyal a http proxy, a socks5 proxy and if these dont work try a rotating proxy

**Comment by hanbit77** [comment]
If I modify your source in app.js like below,
then your bot works very well.

In this moment, Is the proxy server working?

======================================
        for (let proxy of video.proxies) {

	   newProxies.push(proxy)

	    /*
            let works = await proxy_tester(proxy, topArguments.proxyTimeout * 1000)
            if (works) {
                newProxies.push(proxy)
                console.log(color.green(`Proxy "${proxy}" is usable`))
            } else {
                console.log(color.red(`Proxy "${proxy}" is unusable`))
            }
	   */
        }
==========================================

**Comment by JijaProGamer** [comment]
It works for several people. When the browsers launch do the videos launch and the bot watches it fully without crashing?

**Comment by hanbit77** [comment]
Yes, bot is checking the progress of the video very well without crashing.
At that moment, Is the bot using proxy server?

**Comment by JijaProGamer** [comment]
> At that moment, Is the bot using proxy server?

do you mean if it uses proxies? If yes, then yep it does use proxies but you have to provide the proxies youtself

**Comment by hanbit77** [comment]
Thanks~! 
But the total bandwidth usage of proxy server does not increase.
That's the curios point.
I think your bot uses the direct connection not proxy server.

**Comment by JijaProGamer** [comment]
Are you using the latest update? Can I see your options.yaml file?

**Comment by hanbit77** [comment]
![iproyal](https://user-images.githubusercontent.com/121408745/210281435-439a5b63-abc0-43f6-af7e-6d073c1e987d.png)

Here is my config file.!
I fill out video id and id:pass part.

**Comment by JijaProGamer** [comment]
I will fix the proxy checker in the next update, it should appear in max. 2 days

**Comment by hanbit77** [comment]
Thank you very much~~!.
I'll wait for your update!!

**Comment by hanbit77** [comment]
I did some test with fake proxy server.
Because the proxy server is faked one, I had to modify the app.js to bypass server check part.

Here is the modified part of app.js.
![modify_app_js](https://user-images.githubusercontent.com/121408745/210287130-0ca785fd-36d2-4e07-b198-6452c6b913e3.png)

and I put the fake proxy server in options.yaml.
http://fakeid:fakepass@fakeaddress.com:12345 is not exist in the world. 
 
![config_file](https://user-images.githubusercontent.com/121408745/210287205-ce0d75e4-087d-41cc-bed7-b4d7417cd190.png)

In this circumstance your bot is supposed to not be working.
But, your bot works well.
Please, check the code and fix the bug.
Thanks in advance~!

**Comment by hanbit77** [comment]
I made a auth extension folder at node_modules\youtube-selfbot-api\extensions and put 2 files in auth extension foler.
These are backgound.js and manifest.json.

Then I set direct:// for proxy server setting.
It worked for IPRoyal Residential proxies.

I attached 2 files.
If you look those files then you can make the bot for IPRoyal Residential proxies.

[proxy_auth.zip](https://github.com/JijaProGamer/youtubeWatchBot/files/10334087/proxy_auth.zip)

**Comment by JijaProGamer** [comment]
Ill look at what is causing that, thanks

**Comment by JijaProGamer** [comment]
Okay, so untill the next version comes, you can fix this by going into /node_modules/youtube-selfbot-api/handleNewPage.js, go to line 105 and change that line with

```
if (noProxy || !proxy || proxy == "direct://") return request.continue();
```
